# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    dir
  displayName: 'Run a multi-line script'

# # Archive files
# # Compress files into .7z, .tar.gz, or .zip
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(Build.BinariesDirectory)' 
#     includeRootFolder: true 
#     archiveType: 'zip' # Options: zip, 7z, tar, wim
#     #tarCompression: 'gz' # Optional. Options: gz, bz2, xz, none
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' 
#     replaceExistingArchive: true 
#     #verbose: # Optional
#     #quiet: # Optional

- publish: $(System.DefaultWorkingDirectory)/README.md
  artifact: testReadme

# - task: NuGetCommand@2
#   inputs:
#     command: pack
#     packagesToPack: '**/*.md'
#     packDestination: '$(Build.ArtifactStagingDirectory)'


- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: $(Build.DefaultWorkingDirectory)
    vstsFeedPublish: 'pipelineTest/testFeed'
    vstsFeedPackagePublish: 'readme-md'

